steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/arcs-front'
      - '.'

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/arcs-front'

# This will make sure the image gets stored in the container registry
images:
  - 'gcr.io/$PROJECT_ID/arcs-front'

logsBucket: "gs://arcs-front-logs"
